### Programming Assignment 8- NumPy
#### Jameson Buie - Version 1
#### CS-150 Spring 2023

In [1]:
import numpy as np

# a)

In [7]:
array1=np.arange(10,41,10)
array1.resize(2,2)

In [8]:
array1

array([[10, 20],
       [30, 40]])

In [27]:
print("i:\n",array1*array1)
print("ii:\n",array1+100)
print("iii:\n ",array1*5)
print("iv:\n",np.sqrt(array1))

i:
 [[ 100  400]
 [ 900 1600]]
ii:
 [[110 120]
 [130 140]]
iii:
  [[ 50 100]
 [150 200]]
iv:
 [[3.16227766 4.47213595]
 [5.47722558 6.32455532]]


# b)

In [22]:
a2=np.arange(3,28,3)
a2.resize(3,3)
a2

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [24]:
a3=np.linspace(10,20,9)
a3.resize(3,3)
a3

array([[10.  , 11.25, 12.5 ],
       [13.75, 15.  , 16.25],
       [17.5 , 18.75, 20.  ]])

In [25]:
# multiplying the arrays together
a4=np.multiply(a2,a3)
a4

array([[ 30. ,  67.5, 112.5],
       [165. , 225. , 292.5],
       [367.5, 450. , 540. ]])

# c)

In [28]:
import pandas as pd

In [36]:
# loading the files
f1=np.load("process1.npy")
f1

array([[52, 12, 81,  0, 58]], dtype=int32)

In [37]:
f2=np.load("process2.npy")
f2

array([[96,  4, 61, 16, 43]], dtype=int32)

In [38]:
f3=np.load("process3.npy")
f3

array([[38, 96, 45, 17, 58]], dtype=int32)

In [39]:
f4=np.load("process4.npy")
f4

array([[97, 21, 22, 25,  6]], dtype=int32)

In [40]:
f5=np.load("process5.npy")
f5

array([[77,  6, 19,  2, 74]], dtype=int32)

In [43]:
a5=np.vstack([f1,f2,f3,f4,f5])
a5

array([[52, 12, 81,  0, 58],
       [96,  4, 61, 16, 43],
       [38, 96, 45, 17, 58],
       [97, 21, 22, 25,  6],
       [77,  6, 19,  2, 74]], dtype=int32)

In [62]:
# splitting the array by columns
a,b,c,d,e=np.hsplit(a5,5)

In [63]:
# mean of each column
print("The mean of the first column is: ",np.mean(a))
print("The mean of the second column is: ",np.mean(b))
print("The mean of the third column is: ",np.mean(c))
print("The mean of the fourth column is: ",np.mean(d))
print("The mean of the fifth column is: ",np.mean(e))

The mean of the first column is:  72.0
The mean of the second column is:  27.8
The mean of the third column is:  45.6
The mean of the fourth column is:  12.0
The mean of the fifth column is:  47.8
